### ISSUE TITLE
Error creating session.json when behavior videos were not recorded

### ISSUE THREAD

**Issue by LKINSEY** [LKINSEY/MetaDataGUI#1]
issue in prepareSessionJSON when no videos are recorded:
	- when this occurs, this happens --> behavior_data['scanimage_file_names'] = 'no movie files found'
	- this is an issue in the function due to trying to make the Boolean array of "good trials" and "hit trials"
		>> for r,sfn in zip(behavior_data['reward_L'],behavior_data['scanimage_file_names']):
        		&ensp; if type(sfn) == str:
            		&emsp; goodtrials.append(False)
        		&ensp;else:
            		&emsp;	goodtrials.append(True)
        		&ensp;if len(r)==0:
            		&emsp;	hittrials.append(False)
        		&ensp;else:
            		&emsp;	hittrials.append(True)
	- this is an issue because goodtrials becomes length == 20, but behavior_data['reward_L'] is still length == number trials in experiment...
	- this creates something like this later in the function:

for i,j in zip(behavior_data['reward_L'],behavior_data['scanimage_file_names']):
   &emsp; print(i, j)
    
&emsp;&emsp; [4.2178] n
&emsp;&emsp; [4.5397] o
&emsp;&emsp; [8.5257]  
&emsp;&emsp; [4.2094] m
&emsp;&emsp; [4.0163] o
&emsp;&emsp; [4.4891] v
&emsp;&emsp; [7.0645] i
&emsp;&emsp; [6.0741] e
&emsp;&emsp; [5.7221]  
&emsp;&emsp; [6.1709] f
&emsp;&emsp; [] i
&emsp;&emsp; [] l
&emsp;&emsp; [9.6621] e
&emsp;&emsp; [5.879] s
&emsp;&emsp; [9.2404]  
&emsp;&emsp; [] f
&emsp;&emsp; [] o
&emsp;&emsp; [] u
&emsp;&emsp; [] n
&emsp;&emsp; [] d

**Comment by LKINSEY** [comment]
current workaround:

Im going to make a gate that says if no movie files are around, then assume all trials are good trials

   >>  if len(behavior_data['scanimage_file_names'])==20:#if == 'no movie files found'
   &emsp;&emsp;     goodtrials = np.full((1,len(behavior_data['reward_L'])), True)
   &emsp;&emsp;     hittrials = np.where((behavior_data['reward_L'])>0, True, False)
   else:
   &emsp;&emsp;    for r,sfn in zip(behavior_data['reward_L'],behavior_data['scanimage_file_names']):
   &emsp;&emsp;&emsp;&emsp;         if type(sfn) == str:
   &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;             goodtrials.append(False)
   &emsp;&emsp;&emsp;&emsp;         else:
   &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;             goodtrials.append(True)
   &emsp;&emsp;&emsp;&emsp;         if len(r)==0:
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;            hittrials.append(False)
   &emsp;&emsp;&emsp;&emsp;         else:
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;            hittrials.append(True)


I dont know if this is a safe assumption to make for further data processing pipeline, but it resolves the issue temporarily at least

**Comment by rozmar** [comment]
pls use code block with: ```
```
So it will be easier to read your code here
```


I think we are talking about 2 separate things.
There are behavior videos, and 2p videos. The scanimage_file_names are the 2p videos, if there are no 2p videos, there are not trials, nothing should be analyzed.

But it seems like here there are rewards, so there has to be 2p videos, otherwise BCI doesn't work. I am a bit confused. There is nothing in this code about behavior videos.

Can you point me to the line in the code?
Also, which session is this?

**Comment by LKINSEY** [comment]
```
Sure thing, will use ``` moving forward.
```
274-286 of the main_utility.py script

this is the prepareSessionJSON function. Actually I took a look and realized I needed to update what path I was giving this function since I updated the organization of raw data into a pophys folder

**Comment by rozmar** [comment]
So is this resolved?
if so, pls remove this part:
https://github.com/LKINSEY/MetaDataGUI/blob/90d0b9a6b348d0c39e8ea1f553fa5aa093d2a875/main_utility.py#L274

**Comment by LKINSEY** [comment]
fixed:
```

rawDataPath = f'Y:/{WRname}/{dateFileFormat}/pophys'
...
...
extract_behavior(WRname, rawDataPath, behavior_folder_staging)
```
