### ISSUE TITLE
Mouse WR name dropdown menu item goes wild after Process Data

### ISSUE THREAD

**Issue by rozmar** [LKINSEY/MetaDataGUI#2]
Lucas knows what to fix, how to fix

**Comment by rozmar** [comment]
![image](https://github.com/user-attachments/assets/ea35a91e-c950-48bb-a835-8af8976550f1)

**Comment by LKINSEY** [comment]
turns out this was a small typo, should be fixed now but will close after testing

**Comment by rozmar** [comment]
yes it works, awesome!
