### ISSUE TITLE
Error uploading to AWS

### ISSUE THREAD

**Issue by rozmar** [LKINSEY/MetaDataGUI#6]
- The asset name should include the date and time, not just the date
- there was some issue registering to CO.. was the platform wrong?

Lucas knows all the details

**Comment by LKINSEY** [comment]
changed datetime to be datetime.now() - to reflect datetime of upload, however need to figure out a way to get datetime of data acquisition

**Comment by rozmar** [comment]
Data upload works, appears on CO! Awesome!
