### ISSUE TITLE
paths should not be hard coded

### ISSUE THREAD

**Issue by rozmar** [LKINSEY/MetaDataGUI#7]
Right now paths to staging and to the code are hard-coded, so it can effectively run on only one PC.
Paths should be in a json file that will be specific for each computer where the code runs.
The code should pull these paths from the json file.

**Comment by LKINSEY** [comment]
currently in the readme we request to make sure dataDir is mapped to Y drive which I think is ok, I think processing data paths are only other paths that need to be fixed

**Comment by LKINSEY** [comment]
since data requires VAST access, user will need to follow readme to map network drive correctly in order to be compatable with how the gui accesses data
