### ISSUE TITLE
session dropdown list order

### ISSUE THREAD

**Issue by rozmar** [LKINSEY/MetaDataGUI#9]
When the dropdown menu is created, not all the folders should be included, but only the ones that conform the MMDDYY criteria.
Then, they should be transformed to datetime and ordered by date, newest on top, and that should be selected by default.

**Comment by LKINSEY** [comment]
tab feature now selects newest processed data - will clean up drop downs though so all conform to mmddyy format

**Comment by LKINSEY** [comment]
session dates now conform to mmddyy format now and most recent date is displayed at top of drop down
